import ReactMarkdown from "react-markdown";
import type { DocumentSummaryRead } from "@/lib/types";
import { formatDate } from "@/lib/utils";

interface Props {
  summary: DocumentSummaryRead;
  docTitle: string;
  labName: string | null;
  versionDate: string;
  sourceUrl: string | null;
  sourceWordCount: number;
}

export function ChapteredSummary({
  summary, docTitle, labName, versionDate, sourceUrl, sourceWordCount,
}: Props) {
  return (
    <article className="max-w-[68ch]">
      {/* Heading strip */}
      <div className="mb-8 pb-6 border-b border-[var(--border)]">
        <div className="text-xs uppercase tracking-[0.12em] text-[var(--muted)] mb-2">
          Summary
        </div>
        <h2 className="font-serif text-2xl sm:text-3xl font-bold leading-tight mb-3">
          {docTitle}
        </h2>
        <div className="text-sm text-[var(--muted)] leading-relaxed">
          A {summary.total_words.toLocaleString()}-word brief of a{" "}
          {sourceWordCount.toLocaleString()}-word document.
          {labName && <> Published by <span className="text-[var(--text)]">{labName}</span>.</>}
          {" "}Version dated {formatDate(versionDate)}.
        </div>
      </div>

      {/* Chapters */}
      <div className="space-y-10">
        {summary.chapters.map((ch, i) => (
          <section key={i}>
            <div className="flex items-baseline gap-3 mb-3">
              <span className="text-xs tabular-nums text-[var(--muted)] font-mono">
                {String(i + 1).padStart(2, "0")}
              </span>
              <h3 className="font-serif text-xl sm:text-2xl font-bold leading-tight">
                {ch.title}
              </h3>
            </div>
            <div className="prose-chapter text-[15px] leading-[1.8] text-[var(--text)]">
              <ReactMarkdown
                components={{
                  p: ({ children }) => <p className="mb-4">{children}</p>,
                  strong: ({ children }) => (
                    <strong className="font-semibold text-[var(--text)]">{children}</strong>
                  ),
                  em: ({ children }) => <em className="italic">{children}</em>,
                }}
              >
                {ch.prose}
              </ReactMarkdown>
            </div>
          </section>
        ))}
      </div>

      {/* Footer */}
      <footer className="mt-12 pt-6 border-t border-[var(--border)] text-[11px] text-[var(--muted)] leading-relaxed">
        Generated by Claude {summary.model_used} from the cleaned source on{" "}
        {formatDate(summary.generated_at)}. Passages in double quotes are verbatim
        from the source; other text is neutral paraphrase. For citation, use the original:{" "}
        {sourceUrl ? (
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-[var(--accent)] underline hover:opacity-80"
          >
            original document
          </a>
        ) : (
          <span>see source link above</span>
        )}
        {" · "}source SHA <span className="font-mono">{summary.source_hash}</span>.
      </footer>
    </article>
  );
}
